config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  resources :posts
  resources :tags
  resources :replies
  resources :users
  resources :reactions
  resources :series
  resources :follows
  root 'static_pages#index'
  get 'static_pages/question_detail'
  get 'static_pages/question_list'
  get 'static_pages/profile'
  get 'static_pages/login'
  get 'static_pages/register'
end

app/models/post.rb
class Post < ApplicationRecord
  self.inheritance_column = nil
  belongs_to :user
  belongs_to :series, optional: true
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  has_many :replies, -> { where parent_id: nil }, as: :replyable, dependent: :destroy
  has_many :reactions, as: :reactionable, dependent: :destroy
  has_many :views, dependent: :destroy

  acts_as_paranoid

  mount_uploader :cover_image, ImageUploader

  enum type: {article: 0, question: 1}

  validates :title, presence: true, length: {maximum: Settings.post.max_title,
    minimum: Settings.post.min_title}
  validates :content, presence: true

  scope :includes_full, -> do
    merge(include_user).merge(include_tags).merge(include_replies).merge(include_reactions).include_views
  end
  scope :order_by_votes_count, -> do
    joins("LEFT JOIN reactions ON reactions.reactionable_id = posts.id and reactions.reactionable_type = 'Post'
      and (target_type = #{Reaction.target_types[:upvote]} or target_type = #{Reaction.target_types[:downvote]})
      and reactions.deleted_at is NULL")
    .group("posts.id").order "sum(case target_type
      when #{Reaction.target_types[:upvote]} then 1
      when #{Reaction.target_types[:downvote]} then -1
      else 0 end) desc"
  end

  scope :order_by_views_count, -> do
    left_joins(:views).group("posts.id").order("sum(amount) desc, created_at desc").select("posts.*, sum(amount) as views_count")
    .merge(include_user)
  end
  scope :include_user, -> {includes(:user)}
  scope :not_belong_to_series, -> series_id {where series_id: [nil, series_id]}
  private

  scope :include_tags, -> {includes(:tags)}
  scope :include_reactions, -> {includes(:reactions)}
  scope :include_replies, -> {includes(:replies)}
  scope :include_views, -> {includes(:views)}
  # scope :include_replies, -> do
  #   left_joins(:replies).group("posts.id").select("posts.*, count(replies.id) as replies_count")
  # end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user, only: [:new, :create, :show]
  before_action :load_post, only: [:show, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]
  before_action :increase_views_count, only: :show

  def new
    @post = Post.new
  end

  def edit
    @tags = @post.tags
  end

  def index
    @type = params[:type]
    if Post.types.include? @type
      @posts = Post.send(@type).includes_full.page(params[:page]).per Settings.paginate_post
      @popular_posts = Post.send(@type).include_user.order_by_views_count.limit Settings.paginate_little
      @popular_tags = Tag.order_by.posts_count.include_posts_count.limit Settings.paginate_default
      @top_users = User.order_by_point.limit Settings.paginate_little
      respond_to do |format|
        format.js
        format.html
      end
    elsif @type = Series.name.downcase
      @posts = current_user.posts.article.not_belong_to_series(params[:series_id]).includes_full
        .page(params[:page]).per Settings.paginate_default
    else
      respond_to do |format|
        format.js
        format.html {redirect_to root_path}
      end
    end
  end

  def show
    @replies = Reply.by_replyable(@post).order_by_reaction_count.includes_full
    @votes = @post.reactions.include_user
  end

  def create
    @post = current_user.posts.build create_params
    Post.transaction do
      @post.save!
      save_post_tags(@post, params[:tags]) if params[:tags].present?
      flash[:success] = t ".#{@post.type}.flash_success"
      respond_to do |format|
        format.js
      end
    end
  rescue
    @post.errors.add(:tags, t(".tag_error")) if @post.errors.blank?
    respond_to do |format|
      format.js
    end
  end

  def update
    Post.transaction do
      @post.update_attributes update_params
      @post.tags.destroy_all unless @post.tags.pluck(:name).join(",") == params[:tags]
      save_post_tags(@post, params[:tags]) unless @post.tags.pluck(:name).join(",") == params[:tags]
      flash[:success] = t ".#{@post.type}.flash_success"
      respond_to do |format|
        format.js
      end
    end
  rescue
    @post.errors.add(:tags, t(".tag_error")) if @post.errors.blank?
    respond_to do |format|
      format.js
    end
  end

  def destroy
    if @post.destroy
      flash[:success] = t ".#{@post.type}.flash_success"
    else
      flash[:danger] = t ".#{@post.type}.flash_danger"
    end
    respond_to do |format|
      format.json {render json: root_path.to_sym}
    end
  end

  private

  def create_params
    params.require(:post).permit :type, :title, :content, :cover_image
  end

  def update_params
    params.require(:post).permit :title, :content, :cover_image
  end
  def save_post_tags post, tag
    params[:tags].split(",").each do |item|
      @post.post_tags.create! tag: Tag.find_or_create_by!(name: item)
    end
  end

  def load_post
    @post = Post.find_by id: params[:id]
    return if @post
    flash[:danger] = t "flash.load.not_found", resource: Post.name
    redirect_to root_path
  end

  def increase_views_count
    @view = current_user.views.find_or_create_by(post_id: @post.id)
    return if @view.updated_at > Settings.view_timeout.minutes.ago
    @view.update_attributes amount: @view.amount + Settings.one
  end

  def check_user
    return if current_user.id == @post.user_id
    respond_to do |format|
      format.html {redirect_to root_path}
      format.json {render json: false}
      format.js {render}
    end
  end
end

app/helpers/post_helper.rb
module PostHelper
  def list_of_post_types
    Post.types.map{|key, value| [key.capitalize, key]}
  end

  def posts_count posts, type
    group_posts(posts)[type].try(:length) || Settings.zero
  end

  def group_posts posts
    posts.group_by{|post| post.type}
  end

  def views_count views
    views.pluck(:amount).inject(:+) || Settings.zero
  end

  def views_count_of_series posts
    posts.map{|post| views_count post.views}.inject(:+)
  end

  def check_user user_id
    current_user.id == user_id
  end
end

app/views/posts/_children_reply.html.erb
<div class="media-block chidrent-reply ribbon-content
  <%= "hide-replies" if hide_replies? reply_counter %>", id="reply_<%= reply.id %>">
  <div class="media-left">
    <%= link_to reply.user, data: {toggle: "tooltip", placement: "bottom",
      original_title: reply.user.name} do %>
      <% image_tag reply.user.avatar.url, class: "img-border img-xs img-circle" %>
    <% end %>
  </div>
  <div class="media-body no-padding-left reply">
    <div class="mar-btm">
      <h4 class="pull-left">
        <%= link_to reply.user.name, reply.user,
        class: "btn-link text-semibold media-heading box-inline" %>
      </h4>
      <% if check_user reply.user_id %>
        <span class="pull-right">&nbsp;|
          <%= link_to "javascript:void(0)", class: "edit-reply", data: {id: reply.id} do %>
            <i class="fa fa-pencil-square-o margin-right-0" aria-hidden="true"></i>
            <%= t ".edit" %>
          <% end %>
          &nbsp;|&nbsp;
          <%= link_to "javascript:void(0)", class: "delete", data:{controller: :replies, id: reply.id,
            reload: false, klass: t(".reply")} do %>
            <i class="fa fa-trash-o margin-right-0" aria-hidden="true"></i>
            <%= t ".delete" %>
          <% end %>
        </span>
      <% end %>
      <p class="text-muted text-sm pull-right">
        <i class="fa fa-clock-o"></i>
        <%= time_ago_in_words reply.created_at %>
      </p>
    </div>
    <div class="reply-content">
      <%= raw reply.content %>
    </div>
    <div class="row">
      <div class="col-md-12 pad-ver pull-right margin-bottom-30">
        <%= render "posts/reaction_button", reactions: reply.reactions, reactionable: reply %>
      </div>
    </div>
    <div id="reply_form_<%= reply.id %>"></div>
  </div>
</div>

app/views/posts/_popular_post.html.erb
<% if post.question? %>
  <div class="media-group-item article">
    <div class="media">
      <div class="media-left">
        <div class="avatar avatar-md avatar-circle">
          <%= image_tag post.user.avatar.url %>
        </div>
      </div>
      <div class="media-body">
        <h5 class="media-heading"><%= link_to post.title.truncate(35, separator: ''), post, class: "side-post-title" %></h5>
        <%= link_to post.user do %>
          <small class="media-meta"><%= post.user.name %></small>
        <% end %>
        <div class="points pull-right">
          <span class="green-color"><i class="fa fa-eye">&nbsp;</i><%= pluralize post.views_count, t(".view") %></span>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class="media-group-item article">
    <div class="media">
      <div class="media-left">
        <div class="avatar avatar-md avatar-circle img-border-2">
          <%= image_tag post.cover_image.url || "no_cover_image.png",class: "img-responsive middle-img" %>
        </div>
      </div>
      <div class="media-body">
        <h5 class="media-heading"><%= link_to post.title.truncate(35, separator: ' '), post, class: "side-post-title" %></h5>
        <%= link_to post.user do %>
          <small class="media-meta"><%= post.user.name %></small>
        <% end %>
        <div class="points pull-right">
          <span class="green-color"><i class="fa fa-eye">&nbsp;</i><%= pluralize post.views_count, t(".view") %></span>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/_reaction_button.html.erb
<% if reactionable.class.name == Reply.name %>
  <div class="pad-ver pull-right" id="reaction_of_reply_<%= reactionable.id %>">
    <% unless reaction_count(reactions, Settings.reaction.like).zero? %>
      <%= link_to reactions_path(type: reactionable.class.name, id: reactionable.id), class: "liked-list font-size-12", remote: true do %>
        <i class="fa fa-thumbs-up blue-background"></i>
        <%= label_liked_user_list reactions %>
      <% end %>
    <% end %>
    <%= link_to "javascript:void(0)", class: "btn btn-sm btn-default btn-reaction
      #{"reacted" if current_user_reacted? reactions, Settings.reaction.like}",
      data: {toggle: "tooltip", placement: "bottom", original_title: t("reactions.target_type.like"),
      target: "like", id: reactionable.id, type: reactionable.class.name} do %>
      <%= reaction_count reactions, Settings.reaction.like %>
      <i class="fa fa-thumbs-up"></i>
    <% end %>
    <%= link_to "javascript:void(0)", class: "btn btn-sm btn-default btn-reaction
      #{"reacted" if current_user_reacted? reactions, Settings.reaction.spam}",
      data: {toggle: "tooltip", placement: "bottom", target: "spam", id: reactionable.id,
      original_title: t("reactions.target_type.spam"), type: reactionable.class.name} do %>
      <%= reaction_count reactions,  Settings.reaction.spam %>
      <i class="fa fa-thumbs-down"></i>
    <% end %>
  </div>
<% else %>
  <div class="row text-center" id="reaction_of_<%= reactionable.class.name.downcase %>_<%= reactionable.id %>">
    <div class="btn-action">
      <%= link_to "javascript:", class: "btn-vote btn-reaction
        #{"reacted" if current_user_reacted? reactions, Settings.reaction.upvote}",
        data: {target: "upvote", id: reactionable.id, type: reactionable.class.name} do %>
        <i class="fa fa-caret-up" aria-hidden="true"></i>
      <% end %>
    </div>
    <h1 class="red-color bold-text text-center"><%= votes_count reactions %></h1>
    <div class="btn-action">
      <%= link_to "javascript:void(0)", class: "btn-vote btn-reaction
        #{"reacted" if current_user_reacted? reactions, Settings.reaction.downvote}",
        data: {target: "downvote", id: reactionable.id, type: reactionable.class.name} do %>
        <i class="fa fa-caret-down" aria-hidden="true"></i>
      <% end %>
    </div>
  </div>
<% end %>

app/views/posts/_reaction_modal.html.erb
<div class="modal fade" id="reaction_modal">
  <div class="modal-dialog">
    <div class="modal-content reactions-custom-modal">
      <div class="modal-header">
        <h4 class="modal-title"><%= t "reactions.all_reactions" %></h4>
      </div>
      <div class="modal-body">
        <ul class="nav nav-tabs" id="tabContent">
          <li class="active">
            <a href="#likes" data-toggle="tab" class="reacted">
              <i class="fa fa-thumbs-up" aria-hidden="true"></i>
              <%= reaction_count reactions, Settings.reaction.like %>
            </a>
          </li>
        </ul>
        <div class="tab-content reactions-tab">
          <div class="tab-pane active" id="likes">
            <% group_reactions(reactions)[Settings.reaction.like].try(:each) do |like| %>
              <div class="row reaction-user-list">
                <div class="col-md-8">
                  <%= image_tag like.user.avatar.url, class: "img-circle img-25 img-border" %>
                  <%= link_to like.user.name, like.user, class: "padding-left-10" %>
                </div>
                <div class="col-md-4 follow">
                  <% if user_signed_in? && is_following(like.user) %>
                    <%= link_to t(".unfollow"), "javascript:void(0)", class: "btn btn-warning btn-xs pull-right",
                     data:{f_id: like.user.id, f_type: like.user.class.name, method: :delete, id: get_follow_id(like.user)} %>
                  <% elsif user_signed_in? && current_user != like.user %>
                    <%= link_to t(".follow"), "javascript:void(0)", class: "btn btn-success btn-xs pull-right",
                     data:{f_id: like.user.id, f_type: like.user.class.name, method: :post, id: ""} %>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-xs btn-primary btn-accept-edit-comment" data-dismiss="modal">
          <%= t "close" %>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/posts/create.js.erb
<% if flash[:success] %>
  window.location.replace('<%= post_path(@post) %>');
<% else %>
  $('#error_message').html('<%= raw(@post.errors.full_messages.map { |msg| content_tag(:li, msg) }.join) %>');
  swal({
    position: 'top-end',
    type: 'error',
    title: '<%=  t ".#{@post.type}.flash_success" %>',
    showConfirmButton: false,
    timer: 1000
  }).done();
<% end %>

app/views/posts/index.html.erb
 <div class="main-content-area">
    <section class="page-title">
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-sm-7 co-xs-12 text-left">
            <h1><%= t ".#{@type}.page_title" %></h1>
          </div>
          <div class="col-md-6 col-sm-5 co-xs-12 text-right">
            <div class="bread">
              <ol class="breadcrumb">
                <li><%= link_to t("page_title.home"), root_path %></li>
                <li class="active"><%= t ".#{@type}.breadcrumb" %></li>
              </ol>
            </div>
          </div>
        </div>
      </div>
    </section>
    <% if @type == Settings.post.types.question %>
      <section class="section-padding-80 white" id="questions">
        <div class="container">
          <div class="row">
            <div class="col-md-8 col-sm-12">
              <div class="listing">
                <div class="listing-area">
                  <%= render partial: "post", collection: @posts %>
                  <div class="text-center clearfix">
                    <%= paginate @posts %>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-4 col-sm-12">
              <div class="side-bar">
                <div class="widget">
                  <div class="latest-news">
                    <h2><%= t ".#{@type}.popular_post" %></h2>
                    <hr class="widget-separator no-margin">
                    <div class="media-group popular-posts">
                      <%= render partial: "popular_post", collection: @popular_posts, as: :post %>
                    </div>
                    <div class="margin-right-15 pull-right">
                      <%= link_to posts_path(type: :question), class: "green-color" do %>
                        <i class="fa fa-question-circle "></i>
                        <%= t ".#{@type}.all_post" %>
                      <% end %>
                    </div>
                  </div>
                </div>
                <div class="widget">
                  <h2><%= t ".top_users" %></h2>
                  <hr class="widget-separator no-margin">
                  <div class="media-group">
                    <%= render partial: "user", collection: @top_users, as: :user %>
                  </div>
                  <div class="margin-right-15 pull-right">
                    <%= link_to users_path, class: "yellow-color" do %>
                      <i class="fa fa-users"></i>
                      <%= t ".all_users" %>
                    <% end %>
                  </div>
                </div>
                <div class="widget">
                  <div class="widget_tag_cloud">
                    <h2><%= t ".popular_tags" %></h2>
                    <hr class="widget-separator no-margin">
                    <div class="tag_cloud">
                      <% @popular_tags.each do |tag| %>
                        <%= link_to tag do %>
                          <%= tag.name %>
                          <span class="posts-count"><%= tag.posts_count %></span>
                        <% end %>
                      <% end %>
                    </div>
                    <div class="all_tags pull-right">
                      <%= link_to tags_path, class: "red-color" do %>
                        <span class="glyphicon glyphicon-tags"></span>
                        <%= t ".all_tag" %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    <% else %>
      <section id="blog" class="custom-padding white">
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-sm-12">
            <div id="posts-masonry" class="posts-masonry">
              <%= render partial: "post", collection: @posts %>
            </div>
            <div class="clearfix"></div>
            <div class="text-center  section-padding-40">
              <%= paginate @posts %>
            </div>
          </div>
          <div class="col-md-4 col-sm-12">
            <div class="side-bar">
              <div class="widget">
                <div class="latest-news">
                  <h2><%= t ".#{@type}.popular_post" %></h2>
                  <hr class="widget-separator no-margin">
                  <div class="media-group">
                    <%= render partial: "popular_post", collection: @popular_posts, as: :post %>
                  </div>
                  <div class="margin-right-15 pull-right">
                    <%= link_to posts_path(type: :article), class: "green-color" do %>
                      <i class="fa fa-file-text"></i>
                      <%= t ".#{@type}.all_post" %>
                    <% end %>
                  </div>
                </div>
              </div>
              <div class="widget">
                <h2><%= t ".top_users" %></h2>
                <hr class="widget-separator no-margin">
                <div class="media-group">
                  <%= render partial: "user", collection: @top_users, as: :user %>
                </div>
                <div class="margin-right-15 pull-right">
                  <%= link_to users_path, class: "yellow-color" do %>
                    <i class="fa fa-users"></i>
                    <%= t ".all_users" %>
                  <% end %>
                </div>
              </div>
              <div class="widget">
                <div class="widget_tag_cloud">
                  <h2><%= t ".popular_tags" %></h2>
                  <hr class="widget-separator no-margin">
                  <div class="tag_cloud">
                    <% @popular_tags.each do |tag| %>
                      <%= link_to tag do %>
                        <%= tag.name %>
                        <span class="posts-count"><%= tag.posts_count %></span>
                      <% end %>
                    <% end %>
                  </div>
                  <div class="all_tags pull-right">
                    <%= link_to tags_path, class: "red-color" do %>
                      <span class="glyphicon glyphicon-tags"></span>
                      <%= t ".all_tag" %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <% end %>
  </div>

app/views/posts/index.js.erb
<% if @posts.present? %>
  $('#post_list_modal').html('<%= j render "series/post_list_modal", posts: @posts %>');
  if(!$('#post_list_modal').hasClass('in'))
    $('#post_list_modal').modal('hide').modal('show');
  var post_list = $('.post-item');
  var post_ids = $('#post_list_modal').data('post-ids');
  $.each(post_list, function(i) {
    id = parseInt(post_list[i].id);
    if (post_ids.includes(id)) {
      $(post_list[i]).addClass('selected');
    }
  }).done();
<% end %>

app/views/posts/show.html.erb
  <div class="main-content-area">
    <section class="page-title">
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-sm-7 co-xs-12 text-left">
            <h1><%= t ".#{@post.type}.page_title" %></h1>
          </div>
          <div class="col-md-6 col-sm-5 co-xs-12 text-right">
            <div class="bread">
              <ol class="breadcrumb">
                <li><%= link_to t("page_title.home"), root_path %></a></li>
                <li class="active"><%= t ".#{@post.type}.breadcrumb" %></li>
              </ol>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="section-padding-80 white question-details">
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-lg-8 col-sm-12 col-xs-12">
            <div class="listing-grid ">
              <div class="row">
                <div class="col-md-1 col-sm-1 col-xs-2 vote-post">
                  <%= render "posts/reaction_button", reactions: @votes, reactionable: @post %>
                </div>
                <div class="col-md-11 col-sm-11 col-xs-10">
                  <h3><%= @post.title %></h3>
                  <div class="listing-meta">
                    <span>
                      <i class="fa fa-clock-o" aria-hidden="true"></i>
                      <%= time_ago_in_words @post.created_at %>
                    </span>
                    <span>
                      <i class="fa <%= @post.article? ? 'fa-comments' : 'fa-reply' %>" aria-hidden="true"></i>
                      <%= pluralize @post.replies.length, t(".#{@post.type}.reply") %>
                    </span>
                    <span>
                      <i class="fa fa fa-eye" aria-hidden="true"></i>
                      <%= pluralize views_count(@post.views), t(".view") %>
                    </span>
                    <% if check_user @post.user_id %>
                      <span class="pull-right">
                        <%= link_to edit_post_path(@post) do %>
                          <i class="fa fa-pencil-square-o margin-right-0" aria-hidden="true"></i>
                          <%= t ".edit" %>
                        <% end %>
                        &nbsp;|&nbsp;
                        <%= link_to "javascript:void(0)", class: "delete", data:{controller: :posts, id: @post.id,
                          reload: true, klass: t(".#{@post.type}.name")} do %>
                          <i class="fa fa-trash-o margin-right-0" aria-hidden="true"></i>
                          <%= t ".delete" %>
                        <% end %>
                      </span>
                    <% end %>
                  </div>
                </div>
                <div class="col-md-11 col-sm-11 col-xs-10 reply">
                  <div class="post-content margin-bottom-20">
                    <%= raw @post.content %>
                  </div>
                  <div class="row">
                    <div class="col-md-3 col-sm-4 col-xs-12 margin-bottom-30">
                      <%= link_to "javascript:void(0)", data: {replyable_id: @post.id,
                        replyable_type: @post.class.name, type: @post.type, parent_id: ""},
                        class: "show-reply-form btn btn-primary btn-small" do %>
                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                        <%= t ".#{@post.type}.post_reply" %>
                      <% end %>
                    </div>
                    <div class="col-md-9 col-sm-8 col-xs-12 margin-bottom-30">
                      <div class="tagcloud pull-right">
                        <% @post.tags.each do |tag| %>
                          <%= link_to tag.name, tag %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                  <div id="reply_form_"></div>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="thread-reply">
              <h2><%= t ".#{@post.type}.thread_reply" %></h2>
              <%= render partial: "reply", collection: order_replies(@replies) %>
            </div>
          </div>

          <div class="col-md-4 col-sm-12 col-xs-12 clearfix">
            <div class="side-bar">
              <div class="widget">
                <div class="widget-image widget-image-sm">
                  <%= image_tag "light-background.jpg" %>
                  <div class="widget-image-content text-center">
                    <%= image_tag @post.user.avatar.url, class: "img-thumbnail" %>
                    <h2 class="widget-heading text-light"><strong><%= @post.user.name %></strong></h2>
                    <h4 class="widget-heading text-light-op"><em>Graphic Designer</em></h4>
                  </div>
                </div>
                <div class="widget-content widget-content-full border-bottom">
                  <div class="row text-center">
                    <div class="col-xs-6 push-inner-top-bottom border-right">
                      <h3 class="widget-heading"><i class=" icon-trophy push"></i> <br>
                                            <small><strong>34,157</strong> Experience</small></h3>
                    </div>
                    <div class="col-xs-6 push-inner-top-bottom">
                      <h3 class="widget-heading"><i class=" icon-profile-male themed-color-social push"></i> <br>
                                            <small><strong>58.6k</strong> Followers</small></h3>
                    </div>
                  </div>
                </div>
                <div class="widget-content border-bottom">
                  <h4>About</h4>
                  <p>Proin ac nibh rutrum lectus rhoncus eleifend. Sed porttitor pretium venenatis. Suspendisse potenti. Aliquam quis ligula elit.</p>
                  <p>Sed porttitor pretium venenatis. Suspendisse potenti. Aliquam quis ligula elit. Aliquam at orci ac neque semper dictum.</p>
                </div>
                <div class="widget-content">

                  <div class="btn-group"> <a title="" data-toggle="tooltip" class="btn btn-default" href="javascript:void(0)" data-original-title="Facebook"><i class="fa fa-facebook fa-fw"></i></a> <a title="" data-toggle="tooltip" class="btn btn-default" href="javascript:void(0)" data-original-title="Twitter"><i class="fa fa-twitter fa-fw"></i></a> <a title="" data-toggle="tooltip" class="btn btn-default" href="javascript:void(0)" data-original-title="Google Plus"><i class="fa fa-google-plus fa-fw"></i></a> <a title="" data-toggle="tooltip" class="btn btn-default" href="javascript:void(0)" data-original-title="Pinterest"><i class="fa fa-pinterest fa-fw"></i></a> <a title="" data-toggle="tooltip" class="btn btn-default" href="javascript:void(0)" data-original-title="Dribbble"><i class="fa fa-dribbble fa-fw"></i></a> </div>
                </div>
              </div>

              <div class="widget">
                <div class="recent-comments">
                  <h2>Hot Questions</h2>
                  <hr class="widget-separator no-margin">
                  <ul>
                    <li><a href="#">Twitter Bootsrap 3.0 - tabs-left not working anymore?</a>
                    </li>
                    <li><a href="#">Changing the color on my tabbed left bootstrap3 tabs</a>
                    </li>
                    <li><a href="#">How to create tabs on the left in bootstrap.js v3.0.0? </a>
                    </li>
                    <li><a href="#">Bootstrap horizontal form with left floated side tabs</a>
                    </li>
                    <li><a href="#">A Repository class - would you use it to handle multi records? </a>
                    </li>
                    <li><a href="#">Realurl generating unwanted language codes inside url </a>
                    </li>
                    <li><a href="#">post data from html form to php script and return result to ajax/js/jquery </a>
                    </li>
                  </ul>
                </div>
              </div>

              <div class="widget">
                <div class="recent-comments">
                  <h2>Recent Comments</h2>
                  <hr class="widget-separator no-margin">
                  <ul id="recentcomments">
                    <li class="recentcomments"> <span class="comment-author-link">John Doe</span> on <a href="#">bootstrap vs foundation</a> </li>
                    <li class="recentcomments"> <span class="comment-author-link">Emily Copper</span> on <a href="#">how to get data from URL in PHP</a> </li>
                    <li class="recentcomments"> <span class="comment-author-link">Alex Martin</span> on <a href="#">My SQL PHP Multi Layer Drop Down List from Databse</a> </li>
                    <li class="recentcomments"> <span class="comment-author-link">Tina Martin</span> on <a href="#">PHP Multi Layer Drop Down List from Databse</a> </li>
                    <li class="recentcomments"> <span class="comment-author-link">Alex Henz</span> on <a href="#">Can't use custom width with Angular-Slick</a> </li>
                    <li class="recentcomments"> <span class="comment-author-link">Coty Embry</span> on <a href="#">Use Digital Ocean to create node.js server or creating website on Wordpress?</a> </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
  <div id="view_reaction_user_list"></div>

app/views/posts/update.js.erb
<% if flash[:success] %>
  window.location.replace('<%= post_path(@post) %>');
<% else %>
  $('#error_message').html('<%= raw(@post.errors.full_messages.map { |msg| content_tag(:li, msg) }.join) %>');
  swal({
    position: 'top-end',
    type: 'error',
    title: '<%=  t ".#{@post.type}.flash_success" %>',
    showConfirmButton: false,
    timer: 1000
  }).done();
<% end %>