config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  resources :posts
  resources :tags
  resources :replies
  resources :users
  resources :reactions
  resources :series
  resources :follows
  root 'static_pages#index'
  get 'static_pages/question_detail'
  get 'static_pages/question_list'
  get 'static_pages/profile'
  get 'static_pages/login'
  get 'static_pages/register'
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :authenticate_user, only: [:new, :show, :create, :update]
  before_action :load_series, only: [:show, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]
  def index
    @type = Series.name
    @series = Series.includes_full.page(params[:page]).per Settings.paginate_series
    @popular_tags = Tag.order_by.posts_count.include_posts_count.limit Settings.paginate_default
    @top_users = User.order_by_point.limit Settings.paginate_little
    @popular_series = Series.includes_full.order_by_votes_count.limit Settings.paginate_little
  end

  def new
    @series = Series.new
  end

  def show
    @votes = @series.reactions.include_user
    @posts = @series.posts.includes_full
    @replies = Reply.by_replyable(@series).includes_full
    @selected_post_id_list = current_user.posts.article.not_belong_to_series(@series.id)
      .select{|post| post.series_id != nil }.pluck(:id)
  end

  def create
    @series = current_user.series.build series_params
    if @series.save
      flash[:success] = t ".flash_success"
    else
    end
  end

  def update
    if params[:post_ids].nil?
      if @series.update_attributes series_params
        flash[:success] = t ".flash_success.update_series"
      else
        flash[:danger] = t ".flash_danger.update_series"
      end
    else
      Post.transaction do
        post_ids = current_user.posts.article.not_belong_to_series(@series.id).select{|post| post.series_id != nil }.pluck(:id).map(&:to_s)
        add_post_ids =  params[:post_ids].split(',') - post_ids
        remove_post_ids = post_ids - params[:post_ids].split(',')
        add_post_ids.each do |post_id|
          post = current_user.posts.article.find_by id: post_id
          post.update_attributes! series_id: @series.id
        end
        remove_post_ids.each do |post_id|
          post = current_user.posts.article.find_by id: post_id
          post.update_attributes! series_id: nil
        end
      end
      flash[:success] = t ".flash_success.add_posts"
    end
    respond_to do |format|
      format.json {render json: false}
      format.js {render}
    end
  rescue
    flash[:danger] = t ".flash_danger.add_posts"
  end

  def destroy
    if @series.destroy
      flash[:success] = t ".flash_success"
    else
      flash[:danger] = t ".flash_danger"
    end
    respond_to do |format|
      format.json {render json: root_path.to_sym}
    end
  end

  private

  def series_params
    params.require(:series).permit :title, :content, :cover_image
  end

  def load_series
    @series = Series.find_by id: params[:id]
    return if @series
    flash[:danger] = t "flash.load.not_found", resource: Series.name
    redirect_to root_path
  end

  def check_user
    return if @series.user_id == current_user.id
    flash[:danger] = t "flash.check_user.not_allowed", resource: Series.name
    respond_to do |format|
      format.json {render json: false}
      format.html {respond_to root_path}
      format.js {render}
    end
  end
end

app/helpers/series_helper.rb
module SeriesHelper
  def get_tag_list posts
    tag_list = []
    @posts.each do |post|
      post.tags.each do |tag|
        tag_list << tag
      end
    end
    tag_list.uniq
  end

  def views_count_of_series posts
    posts.map{|post| views_count post.views}.inject(:+) || 0
  end
end

app/views/series/_popular_series.html.erb
<div class="media-group-item article">
  <div class="media">
    <div class="media-left">
      <div class="avatar avatar-md avatar-circle img-border-2">
        <%= image_tag series.cover_image.url || "image_series.jpg",class: "img-responsive middle-img" %>
      </div>
    </div>
    <div class="media-body">
      <h5 class="media-heading"><%= link_to series.title.truncate(30, separator: ' '), series, class: "side-post-title" %></h5>
      <%= link_to series.user do %>
        <small class="media-meta"><%= series.user.name %></small>
      <% end %>
      <div class="points pull-right">
        <span class="green-color"><i class="fa fa-sort">&nbsp;</i><%= pluralize votes_count(series.reactions), t(".vote") %></span>
      </div>
    </div>
  </div>
</div>

app/views/series/_post.html.erb
<div class="media-group <%= 'post-item' if type == :update %>" id="<%= post.id %>">
  <div class="media-group-item padding-left-10">
    <div class="media">
      <div class="media-left">
        <div class="avatar popular-img avatar-md avatar-circle img-border-2">
          <%= image_tag post.cover_image.url || "no_cover_image.png",class: "img-responsive middle-img" %>
        </div>
      </div>
      <div class="media-body">
        <% if type == :update %>
          <div class="col-md-11 col-sm-11 co-xs-11">
            <h5 class="media-heading"><%= link_to post.title, post %></h5>
          </div>
          <div class="col-md-1 col-sm-1 co-xs-1 ">
              <i class="fa fa-link cycle-border add-post" data-id="<%= post.id %>"></i>
          </div>
        <% else %>
          <div class="col-md-12 col-sm-12 co-xs-12">
            <h5 class="media-heading"><%= link_to post.title, post %></h5>
          </div>
        <% end %>
        <ul class="like-comment">
          <li>
            <span class="blue-color no-hover"><i class="fa fa-sort"></i><%= votes_count post.reactions %></span>
          </li>
          <li><span class="blue-color no-hover"><i class="icon-chat"></i><%= post.replies.length %></span>
          </li>
          <li><span class="blue-color no-hover"><i class="fa fa-eye"></i><%= post.views.length %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/series/_post_list_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content post-list-custom-modal">
    <div class="modal-header">
      <h4 class="modal-title"><%= t ".add_posts" %></h4>
    </div>
    <div class="modal-body">
      <div class="news-post">
        <%= render partial: "series/post", collection: posts, locals:{type: :update} %>
      </div>
      <div class="text-center  section-padding-40">
        <%= paginate posts, remote: true %>
      </div>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-xs btn-primary" data-dismiss="modal">
        <%= t "close" %>
      </button>
      <button type="button" class="btn btn-xs btn-primary btn-accept-add-posts">
        <%= t "ok" %>
      </button>
    </div>
  </div>
</div>

app/views/series/_series.html.erb
<div class="index series-item">
  <h2 class="post-box-title">
    [<%= link_to series.user.name, series.user, class: "series-user" %>]
    <%= link_to series.title.truncate(55, separator: ' '),
      series, class: "series-title" %>
  </h2>
  <div class="media-group-item padding-left-10">
    <div class="media">
      <div class="media-left">
        <div class="cover-image-series">
          <%= image_tag series.cover_image.url || "image_series.jpg", class: "img-responsive middle-img" %>
        </div>
      </div>
      <div class="media-body">
        <span class="article-time pull-right">
          <i class="fa fa-clock-o" aria-hidden="true"></i>
          <%= time_ago_in_words series.created_at %>
        </span>
        <div class="">
          <span class="badge info-item" data-toggle="tooltip" title="<%= t ".votes" %>">
            <span class="fa fa-sort"> <%= votes_count series.reactions %></span>
          </span>
          <span class="badge info-item" data-toggle="tooltip" title="<%= t ".comments" %>">
            <span class="fa fa-comments-o"> <%= series.replies.length %></span>
          </span>
          <span class="badge info-item" data-toggle="tooltip" title="<%= t ".views" %>">
            <span class="fa fa-eye"> <%= views_count_of_series(series.posts) %></span>
          </span>
        </div>
        <div class="post-content margin-bottom-10 hidden-overflow">
          <%= raw series.content %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/series/create.js.erb
<% if flash[:success] %>
  window.location.replace('<%= series_path(@series) %>');
<% else %>
  $('#error_message').html('<%= raw(@series.errors.full_messages.map { |msg| content_tag(:li, msg) }.join) %>');
  swal({
    position: 'top-end',
    type: 'error',
    title: I18n.t('series.create.flash_danger'),
    showConfirmButton: false,
    timer: 1000
  }).done();
<% end %>

app/views/series/edit.html.erb
<script type="text/javascript">
  CKEDITOR.config.customConfig = '/assets/ckeditor/ckeditor_config.js';
</script>
<div class="main-content-area">
  <section class="page-title">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-sm-7 co-xs-12 text-left">
          <h1><%= t ".page_title" %></h1>
        </div>
        <div class="col-md-6 col-sm-5 co-xs-12 text-right">
          <div class="bread">
            <ol class="breadcrumb">
              <li><%= link_to t("page_title.home"), root_path %></li>
              <li class="active"><%= t ".breadcrumb" %></li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="section-padding-80 white">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-8 ">
          <div class="box-panel">
            <%= form_for @series, remote: true do |f| %>
              <div class="form-group">
                <%= f.label :cover_image %>
                <div class="input-group">
                  <span class="input-group-btn">
                    <span class="btn btn-default btn-file">
                      <%= t ".browse" %>
                      <%= f.file_field :cover_image, accept: Settings.images.accepted_files, id: "imgInp" %>
                    </span>
                  </span>
                  <input type="text" class="form-control" readonly>
                </div>
              </div>
              <div class="form-group">
                <%= f.label :title %><span class="bold-red-text"> *</span>
                <%= f.text_field :title, maxlength: Settings.series.max_title, placeholder: t(".placeholder.title"),
                  minlength: Settings.series.min_title, required: true, class: "form-control" %>
              </div>
              <div class="form-group">
                <label><%= t ".content"%></label>
                <%= f.text_area :content, placeholder: t(".placeholder.content"), class: "form-control ckeditor" %>
              </div>
              <div id="error_message"></div>
              <%= f.submit t(".submit"), class: "btn btn-primary pull-right" %>
            <% end %>
          </div>
        </div>
        <div class="col-sm-12 col-xs-12 col-md-4">

          <!-- sidebar -->
          <div class="side-bar">

            <!-- widget -->
            <div class="widget">
              <div class="recent-comments">
                <h2>Hot Questions</h2>
                <hr class="widget-separator no-margin">
                <ul>
                  <li><a href="#">Twitter Bootsrap 3.0 - tabs-left not working anymore?</a>
                  </li>
                  <li><a href="#">Changing the color on my tabbed left bootstrap3 tabs</a>
                  </li>
                  <li><a href="#">How to create tabs on the left in bootstrap.js v3.0.0? </a>
                  </li>
                  <li><a href="#">A Repository class - would you use it to handle multi records? </a>
                  </li>

                  <li><a href="#">post data from html form to php script and return result to ajax/js/jquery </a>
                  </li>
                </ul>
              </div>
            </div>
            <!-- widget -->

            <!-- widget -->
            <div class="widget">
              <div class="latest-news">
                <h2>Latest News</h2>
                <hr class="widget-separator no-margin">

                <div class="news-post">
                  <div class="post">
                    <figure class="post-thumb"><img alt="" src="images/blog/small-1.png">
                    </figure>
                    <h4><a href="#">Differentiate Yourself And Attract More Attention </a></h4>
                    <div class="post-info">1 hour ago</div>
                  </div>

                  <div class="post">
                    <figure class="post-thumb"><img alt="" src="images/blog/small-2.png">
                    </figure>
                    <h4><a href="#">Differentiate Yourself And Attract More Attention </a></h4>
                    <div class="post-info">1 hour ago</div>
                  </div>

                  <div class="post">
                    <figure class="post-thumb"><img alt="" src="images/blog/small-3.png">
                    </figure>
                    <h4><a href="#">Differentiate Yourself And Attract More Attention </a></h4>
                    <div class="post-info">1 hour ago</div>
                  </div>

                </div>

              </div>
            </div>
            <!-- widget end -->

          </div>
          <!-- sidebar end -->

        </div>
        <!-- Blog Right Sidebar End -->
        <div class="clearfix"></div>
      </div>
    </div>
    <!-- end container -->
  </section>
</div>

app/views/series/index.html.erb
<div class="main-content-area">
  <section class="page-title">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-sm-7 co-xs-12 text-left">
          <h1><%= t ".page_title" %></h1>
        </div>
        <div class="col-md-6 col-sm-5 co-xs-12 text-right">
          <div class="bread">
            <ol class="breadcrumb">
              <li><%= link_to t("page_title.home"), root_path %></a></li>
              <li class="active"><%= t ".breadcrumb" %></li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="section-padding-80 white series" id="questions">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-xs-12 col-md-8">
          <%= render partial: "series", collection: @series %>
        </div>
        <div class="col-sm-12 col-xs-12 col-md-4">
          <div class="side-bar">
            <div class="widget">
              <div class="latest-news">
                <h2><%= t ".popular_series" %></h2>
                <hr class="widget-separator no-margin">
                <div class="media-group popular-posts">
                  <%= render partial: "popular_series", collection: @popular_series, as: :series %>
                </div>
                <div class="margin-right-15 pull-right">
                  <%= link_to series_index_path, class: "green-color" do %>
                    <i class="fa fa-list-alt"></i>
                    <%= t ".all_series" %>
                  <% end %>
                </div>
              </div>
            </div>
            <div class="widget">
              <h2><%= t ".top_users" %></h2>
              <hr class="widget-separator no-margin">
              <div class="media-group">
                <%= render partial: "posts/user", collection: @top_users, as: :user %>
              </div>
              <div class="margin-right-15 pull-right">
                <%= link_to users_path, class: "yellow-color" do %>
                  <i class="fa fa-users"></i>
                  <%= t ".all_users" %>
                <% end %>
              </div>
            </div>
            <div class="widget">
              <div class="widget_tag_cloud">
                <h2><%= t ".popular_tags" %></h2>
                <hr class="widget-separator no-margin">
                <div class="tag_cloud">
                  <% @popular_tags.each do |tag| %>
                    <%= link_to tag do %>
                      <%= tag.name %>
                      <span class="posts-count"><%= tag.posts_count %></span>
                    <% end %>
                  <% end %>
                </div>
                <div class="all_tags pull-right">
                  <%= link_to tags_path, class: "red-color" do %>
                    <span class="glyphicon glyphicon-tags"></span>
                    <%= t ".all_tag" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/series/show.html.erb
  <div class="main-content-area">
    <section class="page-title">
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-sm-7 co-xs-12 text-left">
            <h1><%= t ".page_title" %></h1>
          </div>
          <div class="col-md-6 col-sm-5 co-xs-12 text-right">
            <div class="bread">
              <ol class="breadcrumb">
                <li><%= link_to t("page_title.home"), root_path %></a></li>
                <li class="active"><%= t ".breadcrumb" %></li>
              </ol>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="section-padding-80 white question-details">
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-lg-8 col-sm-12 col-xs-12">
            <div class="listing-grid ">
              <div class="row">
                <div class="col-md-1 col-sm-1 col-xs-2 vote-post">
                  <%= render "posts/reaction_button", reactions: @votes, reactionable: @series %>
                </div>
                <div class="col-md-11 col-sm-11 col-xs-10">
                  <h3><%= @series.title %></h3>
                  <div class="listing-meta">
                    <span>
                      <i class="fa fa-clock-o" aria-hidden="true"></i>
                      <%= time_ago_in_words @series.created_at %>
                    </span>
                    <span>
                      <i class="fa fa-comments %>" aria-hidden="true"></i>
                      <%= pluralize @series.replies.length, t(".comment") %>
                    </span>
                    <span>
                      <i class="fa fa fa-eye" aria-hidden="true"></i>
                      <%= pluralize views_count_of_series(@posts), t(".view") %>
                    </span>
                    <% if check_user @series.user_id %>
                      <span class="pull-right">
                        <%= link_to edit_series_path(@series) do %>
                          <i class="fa fa-pencil-square-o margin-right-0" aria-hidden="true"></i>
                          <%= t ".edit" %>
                        <% end %>
                        &nbsp;|&nbsp;
                        <%= link_to "javascript:void(0)", class: "delete", data:{controller: :series, id: @series.id,
                          reload: true, klass: t(".series")} do %>
                          <i class="fa fa-trash-o margin-right-0" aria-hidden="true"></i>
                          <%= t ".delete" %>
                        <% end %>
                      </span>
                    <% end %>
                  </div>
                </div>
                <div class="col-md-11 col-sm-11 col-xs-10 reply">
                  <div class="post-content margin-bottom-20">
                    <%= raw @series.content %>
                  </div>
                  <div class="row">
                    <%if @posts.present? %>
                      <div class="col-md-12 col-sm-12 col-xs-12 margin-bottom-30">
                        <div class="tagcloud pull-left">
                          <% get_tag_list(@posts).each do |tag| %>
                            <%= link_to tag.name, tag %>
                          <% end %>
                        </div>
                      </div>
                      <div class="col-md-12 col-sm-12 col-xs-12 margin-bottom-30">
                        <div class="post-list-custom-modal post-list">
                          <div class="section-title-line">
                            <h1 class="text-bold"><%= t ".aritcle_list" %></h1>
                            <hr class="filler-line mb-05">
                          </div>
                          <%= render partial: "series/post", collection: @posts, locals:{type: :show} %>
                        </div>
                      </div>
                    <% end %>
                    <div class="col-md-6 col-sm-6 col-xs-12 margin-bottom-30">
                      <%= link_to "javascript:void(0)", data: {replyable_id: @series.id,
                        replyable_type: @series.class.name, type: :article, parent_id: ""},
                        class: "show-reply-form btn btn-primary btn-small" do %>
                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                        <%= t ".post_reply" %>
                      <% end %>
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-12 margin-bottom-30">
                      <% if check_user @series.user_id %>
                        <%= link_to posts_path(type: :series, series_id: @series.id), remote: true,
                          class: "btn btn-primary btn-small pull-right" do %>
                          <i class="fa fa-plus-circle " aria-hidden="true"></i>
                          <%= t ".add_posts" %>
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                  <div id="reply_form_"></div>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="thread-reply">
              <h2><%= t ".thread_reply" %></h2>
              <%= render partial: "posts/reply", collection: order_replies(@replies) %>
            </div>
          </div>

          <div class="col-md-4 col-sm-12 col-xs-12 clearfix">
            <div class="side-bar">
              <div class="widget">
                <div class="widget-image widget-image-sm">
                  <%= image_tag "light-background.jpg" %>
                  <div class="widget-image-content text-center">
                    <%= image_tag @series.user.avatar.url, class: "img-thumbnail" %>
                    <h2 class="widget-heading text-light"><strong><%= @series.user.name %></strong></h2>
                    <h4 class="widget-heading text-light-op"><em>Graphic Designer</em></h4>
                  </div>
                </div>
                <div class="widget-content widget-content-full border-bottom">
                  <div class="row text-center">
                    <div class="col-xs-6 push-inner-top-bottom border-right">
                      <h3 class="widget-heading"><i class=" icon-trophy push"></i> <br>
                                            <small><strong>34,157</strong> Experience</small></h3>
                    </div>
                    <div class="col-xs-6 push-inner-top-bottom">
                      <h3 class="widget-heading"><i class=" icon-profile-male themed-color-social push"></i> <br>
                                            <small><strong>58.6k</strong> Followers</small></h3>
                    </div>
                  </div>
                </div>
                <div class="widget-content border-bottom">
                  <h4>About</h4>
                  <p>Proin ac nibh rutrum lectus rhoncus eleifend. Sed porttitor pretium venenatis. Suspendisse potenti. Aliquam quis ligula elit.</p>
                  <p>Sed porttitor pretium venenatis. Suspendisse potenti. Aliquam quis ligula elit. Aliquam at orci ac neque semper dictum.</p>
                </div>
                <div class="widget-content">

                  <div class="btn-group"> <a title="" data-toggle="tooltip" class="btn btn-default" href="javascript:void(0)" data-original-title="Facebook"><i class="fa fa-facebook fa-fw"></i></a> <a title="" data-toggle="tooltip" class="btn btn-default" href="javascript:void(0)" data-original-title="Twitter"><i class="fa fa-twitter fa-fw"></i></a> <a title="" data-toggle="tooltip" class="btn btn-default" href="javascript:void(0)" data-original-title="Google Plus"><i class="fa fa-google-plus fa-fw"></i></a> <a title="" data-toggle="tooltip" class="btn btn-default" href="javascript:void(0)" data-original-title="Pinterest"><i class="fa fa-pinterest fa-fw"></i></a> <a title="" data-toggle="tooltip" class="btn btn-default" href="javascript:void(0)" data-original-title="Dribbble"><i class="fa fa-dribbble fa-fw"></i></a> </div>
                </div>
              </div>

              <div class="widget">
                <div class="recent-comments">
                  <h2>Hot Questions</h2>
                  <hr class="widget-separator no-margin">
                  <ul>
                    <li><a href="#">Twitter Bootsrap 3.0 - tabs-left not working anymore?</a>
                    </li>
                    <li><a href="#">Changing the color on my tabbed left bootstrap3 tabs</a>
                    </li>
                    <li><a href="#">How to create tabs on the left in bootstrap.js v3.0.0? </a>
                    </li>
                    <li><a href="#">Bootstrap horizontal form with left floated side tabs</a>
                    </li>
                    <li><a href="#">A Repository class - would you use it to handle multi records? </a>
                    </li>
                    <li><a href="#">Realurl generating unwanted language codes inside url </a>
                    </li>
                    <li><a href="#">post data from html form to php script and return result to ajax/js/jquery </a>
                    </li>
                  </ul>
                </div>
              </div>

              <div class="widget">
                <div class="recent-comments">
                  <h2>Recent Comments</h2>
                  <hr class="widget-separator no-margin">
                  <ul id="recentcomments">
                    <li class="recentcomments"> <span class="comment-author-link">John Doe</span> on <a href="#">bootstrap vs foundation</a> </li>
                    <li class="recentcomments"> <span class="comment-author-link">Emily Copper</span> on <a href="#">how to get data from URL in PHP</a> </li>
                    <li class="recentcomments"> <span class="comment-author-link">Alex Martin</span> on <a href="#">My SQL PHP Multi Layer Drop Down List from Databse</a> </li>
                    <li class="recentcomments"> <span class="comment-author-link">Tina Martin</span> on <a href="#">PHP Multi Layer Drop Down List from Databse</a> </li>
                    <li class="recentcomments"> <span class="comment-author-link">Alex Henz</span> on <a href="#">Can't use custom width with Angular-Slick</a> </li>
                    <li class="recentcomments"> <span class="comment-author-link">Coty Embry</span> on <a href="#">Use Digital Ocean to create node.js server or creating website on Wordpress?</a> </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
  <div id="view_reaction_user_list"></div>
  <div class="modal fade" id="post_list_modal" data-post-ids='<%= @selected_post_id_list %>'
    data-current='<%= @selected_post_id_list %>'></div>
  <div class="modal fade" id="post_list_modal1" data-post-ids='<%= @selected_post_id_list %>'
    data-current='<%= @selected_post_id_list %>'></div>

app/views/series/update.js.erb
<% if flash[:success] %>
  window.location.replace('<%= series_path(@series) %>');
<% else %>
  $('#error_message').html('<%= raw(@series.errors.full_messages.map { |msg| content_tag(:li, msg) }.join) %>');
  swal({
    position: 'top-end',
    type: 'error',
    title: I18n.t('series.update.flash_danger.update_series'),
    showConfirmButton: false,
    timer: 1000
  }).done();
<% end %>