config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  resources :posts
  resources :tags
  resources :replies
  resources :users
  resources :reactions
  resources :series
  resources :follows
  root 'static_pages#index'
  get 'static_pages/question_detail'
  get 'static_pages/question_list'
  get 'static_pages/profile'
  get 'static_pages/login'
  get 'static_pages/register'
end

app/views/layouts/_footer.html.erb
<footer class="footer-area">
  <div class="footer-copyright">
    <div class="auto-container clearfix">
      <!--Copyright-->
      <div class="copyright text-center">Copyright 2016 &copy; Theme Created By <a target="_blank" href="http://themeforest.net/user/scriptsbundle/portfolio">Scriptsbundle</a> All Rights Reserved</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="top-bar">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-md-4 col-sm-6 col-xs-4">
        <ul class="top-nav nav-left">
          <li><%= link_to t(".home"), root_path %></li>
          <li class="hidden-xs"><a href="blog.html">Blog</a>
          </li>
          <li  class="hidden-xs"><a href="contact.html">Contact Us</a>
          </li>
        </ul>
      </div>
      <div class="col-lg-8 col-md-8 col-sm-6 col-xs-8">
        <ul class="top-nav nav-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <%= link_to "javascript:", class: "dropdown-toggle",
                data: {hover: "dropdown", tooggle: "dropdown", animations: "fadeInUp"} do %>
                <%= image_tag current_user.avatar.url, class: "img-circle resize" %>
                <span class="hidden-xs small-padding">
                  <span><%= current_user.name %></span>
                  <i class="fa fa-caret-down"></i>
                </span>
              <% end %>
              <ul class="dropdown-menu ">
                <li><a href="profile.html"><i class=" icon-bargraph"></i> Dashboard</a></li>
                <li>
                  <%= link_to edit_user_registration_path do %>
                    <i class="icon-gears"></i>
                    <%= t ".profile_setting" %>
                  <% end %>
                </li>
                <li><a href="question-list.html"><i class="icon-heart"></i> Questions</a></li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete do %>
                    <i class="icon-lock"></i>
                    <%= t ".signout" %>
                  <% end %>
                </li>
              </ul>
            </li>
          <% else %>
            <li>
              <%= link_to new_user_session_path do %>
                <i class="fa fa-lock" aria-hidden="true"></i>
                <%= t ".login" %>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path do %>
                <i class="fa fa-user-plus" aria-hidden="true"></i>
                <%= t ".signup" %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button">  <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "logo.png", class: "img-responsive" %>
      <% end %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="hidden-sm">
          <%= link_to t(".article"), posts_path(type: :article), class: "#{"red-color" if params[:type] == "article"}" %>
        </li>
        <li class="hidden-sm">
          <%= link_to t(".question"), posts_path(type: :question), class: "#{"red-color" if params[:type] == "question"}" %>
        </li>
        <li class="hidden-sm">
          <%= link_to t(".series"), series_index_path, class: "#{"red-color" if @type == Series.name }" %>
        </li>
        <% if @type == Series.name %>
          <li>
            <div class="btn-nav">
              <%= link_to t(".create_series"), new_series_path, class: "btn btn-primary btn-small navbar-btn" %>
            </div>
          </li>
        <% else %>
          <li>
            <div class="btn-nav">
              <%= link_to t(".create_post"), new_post_path, class: "btn btn-primary btn-small navbar-btn" %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ITF</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div id="flash_message">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %> fade in"><%= value %></div>
      <% end %>
    </div>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>